; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = irradiance_node
; default_envs = ambient_node
; default_envs = surface_node
default_envs = bridge_node

; default_envs = receiver_outdoor
; default_envs = esp01_all
; default_envs = esp01_transciever
; default_envs = devkit_irradiance
; default_envs = xiao_ambient
; default_envs = xiao_ambient_ota
; default_envs = xiao_surface_ota
; default_envs = xiao_surface
; default_envs = promini_acdc
; default_envs = esp01_all
; default_envs = promini_test
; default_envs = esp32s3_test
; default_envs = promini_test
; default_envs = ota_tx

[env]
framework = arduino
build_flags = -Iinclude

[env:irradiance_node]
platform = espressif32
board = esp32doit-devkit-v1
build_src_filter = +<main_irradiance.cpp>
lib_deps = 
    https://github.com/peterus/INA226Lib.git
    https://github.com/adafruit/Adafruit_AHTX0.git
    https://github.com/ayushsharma82/ElegantOTA.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:ambient_node]
platform = espressif32
board = seeed_xiao_esp32c3
build_src_filter = +<main_ambient.cpp>
lib_deps = 
	https://github.com/claws/BH1750.git
    https://github.com/RobTillaart/SHT2x.git
    https://github.com/ayushsharma82/ElegantOTA.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:surface_node]
platform = espressif32
board = seeed_xiao_esp32c3
build_src_filter = +<main_surface.cpp>
lib_deps =
    https://github.com/PaulStoffregen/OneWire.git
    https://github.com/milesburton/Arduino-Temperature-Control-Library.git
    https://github.com/ayushsharma82/ElegantOTA.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:bridge_node]
platform = espressif32
board = esp32doit-devkit-v1
build_src_filter = +<main_bridge.cpp>
lib_deps = 
    https://github.com/ayushsharma82/ElegantOTA.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

; SEPARATOR




[env:xiao_surface]
platform = espressif32
board = seeed_xiao_esp32c3
lib_deps =
    https://github.com/PaulStoffregen/OneWire.git
    https://github.com/milesburton/Arduino-Temperature-Control-Library.git

[env:promini_acdc]
platform = atmelavr
board = micro
lib_deps =
    https://github.com/mandulaj/PZEM-004T-v30.git
    https://github.com/RobTillaart/ADS1X15.git

[env:promini_test]
platform = atmelavr
board = micro
lib_deps =
    ; https://github.com/adafruit/Adafruit_ADS1X15.git
    ; https://github.com/RobTillaart/ADS1X15.git
    https://github.com/mandulaj/PZEM-004T-v30.git

[env:esp01_all]
platform = espressif8266
board = esp01

[env:esp01_transciever]
platform = espressif8266
board = esp01
lib_deps =
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    https://github.com/bblanchon/ArduinoJson.git

[env:esp32s3_test]
platform = espressif32
board = lolin_s3_mini

[env:ota_rx]
platform = espressif32
board = lolin_s3_mini

[env:ota_tx]
platform = espressif32
board = lolin_s3_mini
lib_deps = 
	; https://github.com/claws/BH1750.git
    ; https://github.com/RobTillaart/SHT2x.git
    https://github.com/ayushsharma82/ElegantOTA.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:receiver_outdoor]
platform = espressif32
board = esp32doit-devkit-v1